/* Generated By:JavaCC: Do not edit this line. SqlParserImplConstants.java */
package org.apache.calcite.sql.parser.impl;

public interface SqlParserImplConstants {

  int EOF = 0;
  int A = 1;
  int ABS = 2;
  int ABSENT = 3;
  int ABSOLUTE = 4;
  int ACTION = 5;
  int ADA = 6;
  int ADD = 7;
  int ADMIN = 8;
  int AFTER = 9;
  int ALL = 10;
  int ALLOCATE = 11;
  int ALLOW = 12;
  int ALTER = 13;
  int ALWAYS = 14;
  int AND = 15;
  int ANY = 16;
  int APPLY = 17;
  int ARE = 18;
  int ARRAY = 19;
  int ARRAY_AGG = 20;
  int ARRAY_CONCAT_AGG = 21;
  int ARRAY_MAX_CARDINALITY = 22;
  int AS = 23;
  int ASC = 24;
  int ASENSITIVE = 25;
  int ASSERTION = 26;
  int ASSIGNMENT = 27;
  int ASYMMETRIC = 28;
  int AT = 29;
  int ATOMIC = 30;
  int ATTRIBUTE = 31;
  int ATTRIBUTES = 32;
  int AUTHORIZATION = 33;
  int AVG = 34;
  int BEFORE = 35;
  int BEGIN = 36;
  int BEGIN_FRAME = 37;
  int BEGIN_PARTITION = 38;
  int BERNOULLI = 39;
  int BETWEEN = 40;
  int BIGINT = 41;
  int BINARY = 42;
  int BIT = 43;
  int BLOB = 44;
  int BOOLEAN = 45;
  int BOTH = 46;
  int BREADTH = 47;
  int BY = 48;
  int C = 49;
  int CALL = 50;
  int CALLED = 51;
  int CARDINALITY = 52;
  int CASCADE = 53;
  int CASCADED = 54;
  int CASE = 55;
  int CAST = 56;
  int CATALOG = 57;
  int CATALOG_NAME = 58;
  int CEIL = 59;
  int CEILING = 60;
  int CENTURY = 61;
  int CHAIN = 62;
  int CHAR = 63;
  int CHAR_LENGTH = 64;
  int CHARACTER = 65;
  int CHARACTER_LENGTH = 66;
  int CHARACTER_SET_CATALOG = 67;
  int CHARACTER_SET_NAME = 68;
  int CHARACTER_SET_SCHEMA = 69;
  int CHARACTERISTICS = 70;
  int CHARACTERS = 71;
  int CHECK = 72;
  int CLASSIFIER = 73;
  int CLASS_ORIGIN = 74;
  int CLOB = 75;
  int CLOSE = 76;
  int COALESCE = 77;
  int COBOL = 78;
  int COLLATE = 79;
  int COLLATION = 80;
  int COLLATION_CATALOG = 81;
  int COLLATION_NAME = 82;
  int COLLATION_SCHEMA = 83;
  int COLLECT = 84;
  int COLUMN = 85;
  int COLUMN_NAME = 86;
  int COMMAND_FUNCTION = 87;
  int COMMAND_FUNCTION_CODE = 88;
  int COMMIT = 89;
  int COMMITTED = 90;
  int CONDITION = 91;
  int CONDITIONAL = 92;
  int CONDITION_NUMBER = 93;
  int CONNECT = 94;
  int CONNECTION = 95;
  int CONNECTION_NAME = 96;
  int CONSTRAINT = 97;
  int CONSTRAINT_CATALOG = 98;
  int CONSTRAINT_NAME = 99;
  int CONSTRAINT_SCHEMA = 100;
  int CONSTRAINTS = 101;
  int CONSTRUCTOR = 102;
  int CONTAINS = 103;
  int CONTINUE = 104;
  int CONVERT = 105;
  int CORR = 106;
  int CORRESPONDING = 107;
  int COUNT = 108;
  int COVAR_POP = 109;
  int COVAR_SAMP = 110;
  int CREATE = 111;
  int CROSS = 112;
  int CUBE = 113;
  int CUME_DIST = 114;
  int CURRENT = 115;
  int CURRENT_CATALOG = 116;
  int CURRENT_DATE = 117;
  int CURRENT_DEFAULT_TRANSFORM_GROUP = 118;
  int CURRENT_PATH = 119;
  int CURRENT_ROLE = 120;
  int CURRENT_ROW = 121;
  int CURRENT_SCHEMA = 122;
  int CURRENT_TIME = 123;
  int CURRENT_TIMESTAMP = 124;
  int CURRENT_TRANSFORM_GROUP_FOR_TYPE = 125;
  int CURRENT_USER = 126;
  int CURSOR = 127;
  int CURSOR_NAME = 128;
  int CYCLE = 129;
  int DATA = 130;
  int DATABASE = 131;
  int DATE = 132;
  int DATE_TRUNC = 133;
  int DATETIME = 134;
  int DATETIME_INTERVAL_CODE = 135;
  int DATETIME_INTERVAL_PRECISION = 136;
  int DAY = 137;
  int DAYS = 138;
  int DEALLOCATE = 139;
  int DEC = 140;
  int DECADE = 141;
  int DECIMAL = 142;
  int DECLARE = 143;
  int DEFAULT_ = 144;
  int DEFAULTS = 145;
  int DEFERRABLE = 146;
  int DEFERRED = 147;
  int DEFINE = 148;
  int DEFINED = 149;
  int DEFINER = 150;
  int DEGREE = 151;
  int DELETE = 152;
  int DENSE_RANK = 153;
  int DEPTH = 154;
  int DEREF = 155;
  int DERIVED = 156;
  int DESC = 157;
  int DESCRIBE = 158;
  int DESCRIPTION = 159;
  int DESCRIPTOR = 160;
  int DETERMINISTIC = 161;
  int DIAGNOSTICS = 162;
  int DISALLOW = 163;
  int DISCONNECT = 164;
  int DISPATCH = 165;
  int DISTINCT = 166;
  int DOMAIN = 167;
  int DOT_FORMAT = 168;
  int DOUBLE = 169;
  int DOW = 170;
  int DOY = 171;
  int DROP = 172;
  int DYNAMIC = 173;
  int DYNAMIC_FUNCTION = 174;
  int DYNAMIC_FUNCTION_CODE = 175;
  int EACH = 176;
  int ELEMENT = 177;
  int ELSE = 178;
  int EMPTY = 179;
  int ENCODING = 180;
  int END = 181;
  int END_EXEC = 182;
  int END_FRAME = 183;
  int END_PARTITION = 184;
  int EPOCH = 185;
  int EQUALS = 186;
  int ERROR = 187;
  int ESCAPE = 188;
  int EVERY = 189;
  int EXCEPT = 190;
  int EXCEPTION = 191;
  int EXCLUDE = 192;
  int EXCLUDING = 193;
  int EXEC = 194;
  int EXECUTE = 195;
  int EXISTS = 196;
  int EXP = 197;
  int EXPLAIN = 198;
  int EXTEND = 199;
  int EXTERNAL = 200;
  int EXTRACT = 201;
  int FALSE = 202;
  int FETCH = 203;
  int FILTER = 204;
  int FINAL = 205;
  int FIRST = 206;
  int FIRST_VALUE = 207;
  int FLOAT = 208;
  int FLOOR = 209;
  int FOLLOWING = 210;
  int FOR = 211;
  int FORMAT = 212;
  int FOREIGN = 213;
  int FORTRAN = 214;
  int FOUND = 215;
  int FRAC_SECOND = 216;
  int FRAME_ROW = 217;
  int FREE = 218;
  int FRIDAY = 219;
  int FROM = 220;
  int FULL = 221;
  int FUNCTION = 222;
  int FUSION = 223;
  int G = 224;
  int GENERAL = 225;
  int GENERATED = 226;
  int GEOMETRY = 227;
  int GET = 228;
  int GLOBAL = 229;
  int GO = 230;
  int GOTO = 231;
  int GRANT = 232;
  int GRANTED = 233;
  int GROUP = 234;
  int GROUP_CONCAT = 235;
  int GROUPING = 236;
  int GROUPS = 237;
  int HAVING = 238;
  int HIERARCHY = 239;
  int HOLD = 240;
  int HOP = 241;
  int HOUR = 242;
  int HOURS = 243;
  int IDENTITY = 244;
  int IGNORE = 245;
  int ILIKE = 246;
  int IMMEDIATE = 247;
  int IMMEDIATELY = 248;
  int IMPLEMENTATION = 249;
  int IMPORT = 250;
  int IN = 251;
  int INCLUDE = 252;
  int INCLUDING = 253;
  int INCREMENT = 254;
  int INDICATOR = 255;
  int INITIAL = 256;
  int INITIALLY = 257;
  int INNER = 258;
  int INOUT = 259;
  int INPUT = 260;
  int INSENSITIVE = 261;
  int INSERT = 262;
  int INSTANCE = 263;
  int INSTANTIABLE = 264;
  int INT = 265;
  int INTEGER = 266;
  int INTERSECT = 267;
  int INTERSECTION = 268;
  int INTERVAL = 269;
  int INTO = 270;
  int INVOKER = 271;
  int IS = 272;
  int ISODOW = 273;
  int ISOYEAR = 274;
  int ISOLATION = 275;
  int JAVA = 276;
  int JOIN = 277;
  int JSON = 278;
  int JSON_ARRAY = 279;
  int JSON_ARRAYAGG = 280;
  int JSON_EXISTS = 281;
  int JSON_OBJECT = 282;
  int JSON_OBJECTAGG = 283;
  int JSON_QUERY = 284;
  int JSON_VALUE = 285;
  int K = 286;
  int KEY = 287;
  int KEY_MEMBER = 288;
  int KEY_TYPE = 289;
  int LABEL = 290;
  int LAG = 291;
  int LANGUAGE = 292;
  int LARGE = 293;
  int LAST = 294;
  int LAST_VALUE = 295;
  int LATERAL = 296;
  int LEAD = 297;
  int LEADING = 298;
  int LEFT = 299;
  int LENGTH = 300;
  int LEVEL = 301;
  int LIBRARY = 302;
  int LIKE = 303;
  int LIKE_REGEX = 304;
  int LIMIT = 305;
  int LN = 306;
  int LOCAL = 307;
  int LOCALTIME = 308;
  int LOCALTIMESTAMP = 309;
  int LOCATOR = 310;
  int LOWER = 311;
  int M = 312;
  int MAP = 313;
  int MATCH = 314;
  int MATCHED = 315;
  int MATCHES = 316;
  int MATCH_NUMBER = 317;
  int MATCH_RECOGNIZE = 318;
  int MAX = 319;
  int MAXVALUE = 320;
  int MEASURES = 321;
  int MEMBER = 322;
  int MERGE = 323;
  int MESSAGE_LENGTH = 324;
  int MESSAGE_OCTET_LENGTH = 325;
  int MESSAGE_TEXT = 326;
  int METHOD = 327;
  int MICROSECOND = 328;
  int MILLISECOND = 329;
  int MILLENNIUM = 330;
  int MIN = 331;
  int MINUTE = 332;
  int MINUTES = 333;
  int MINVALUE = 334;
  int MOD = 335;
  int MODIFIES = 336;
  int MODULE = 337;
  int MONDAY = 338;
  int MONTH = 339;
  int MONTHS = 340;
  int MORE_ = 341;
  int MULTISET = 342;
  int MUMPS = 343;
  int NAME = 344;
  int NAMES = 345;
  int NANOSECOND = 346;
  int NATIONAL = 347;
  int NATURAL = 348;
  int NCHAR = 349;
  int NCLOB = 350;
  int NESTING = 351;
  int NEW = 352;
  int NEXT = 353;
  int NO = 354;
  int NONE = 355;
  int NORMALIZE = 356;
  int NORMALIZED = 357;
  int NOT = 358;
  int NTH_VALUE = 359;
  int NTILE = 360;
  int NULL = 361;
  int NULLABLE = 362;
  int NULLIF = 363;
  int NULLS = 364;
  int NUMBER = 365;
  int NUMERIC = 366;
  int OBJECT = 367;
  int OCCURRENCES_REGEX = 368;
  int OCTET_LENGTH = 369;
  int OCTETS = 370;
  int OF = 371;
  int OFFSET = 372;
  int OLD = 373;
  int OMIT = 374;
  int ON = 375;
  int ONE = 376;
  int ONLY = 377;
  int OPEN = 378;
  int OPTION = 379;
  int OPTIONS = 380;
  int OR = 381;
  int ORDER = 382;
  int ORDERING = 383;
  int ORDINALITY = 384;
  int OTHERS = 385;
  int OUT = 386;
  int OUTER = 387;
  int OUTPUT = 388;
  int OVER = 389;
  int OVERLAPS = 390;
  int OVERLAY = 391;
  int OVERRIDING = 392;
  int PAD = 393;
  int PARAMETER = 394;
  int PARAMETER_MODE = 395;
  int PARAMETER_NAME = 396;
  int PARAMETER_ORDINAL_POSITION = 397;
  int PARAMETER_SPECIFIC_CATALOG = 398;
  int PARAMETER_SPECIFIC_NAME = 399;
  int PARAMETER_SPECIFIC_SCHEMA = 400;
  int PARTIAL = 401;
  int PARTITION = 402;
  int PASCAL = 403;
  int PASSING = 404;
  int PASSTHROUGH = 405;
  int PAST = 406;
  int PATH = 407;
  int PATTERN = 408;
  int PER = 409;
  int PERCENT = 410;
  int PERCENTILE_CONT = 411;
  int PERCENTILE_DISC = 412;
  int PERCENT_RANK = 413;
  int PERIOD = 414;
  int PERMUTE = 415;
  int PIVOT = 416;
  int PLACING = 417;
  int PLAN = 418;
  int PLI = 419;
  int PORTION = 420;
  int POSITION = 421;
  int POSITION_REGEX = 422;
  int POWER = 423;
  int PRECEDES = 424;
  int PRECEDING = 425;
  int PRECISION = 426;
  int PREPARE = 427;
  int PRESERVE = 428;
  int PREV = 429;
  int PRIMARY = 430;
  int PRIOR = 431;
  int PRIVILEGES = 432;
  int PROCEDURE = 433;
  int PUBLIC = 434;
  int QUARTER = 435;
  int QUARTERS = 436;
  int RANGE = 437;
  int RANK = 438;
  int READ = 439;
  int READS = 440;
  int REAL = 441;
  int RECURSIVE = 442;
  int REF = 443;
  int REFERENCES = 444;
  int REFERENCING = 445;
  int REGR_AVGX = 446;
  int REGR_AVGY = 447;
  int REGR_COUNT = 448;
  int REGR_INTERCEPT = 449;
  int REGR_R2 = 450;
  int REGR_SLOPE = 451;
  int REGR_SXX = 452;
  int REGR_SXY = 453;
  int REGR_SYY = 454;
  int RELATIVE = 455;
  int RELEASE = 456;
  int REPEATABLE = 457;
  int REPLACE = 458;
  int RESET = 459;
  int RESPECT = 460;
  int RESTART = 461;
  int RESTRICT = 462;
  int RESULT = 463;
  int RETURN = 464;
  int RETURNED_CARDINALITY = 465;
  int RETURNED_LENGTH = 466;
  int RETURNED_OCTET_LENGTH = 467;
  int RETURNED_SQLSTATE = 468;
  int RETURNING = 469;
  int RETURNS = 470;
  int REVOKE = 471;
  int RIGHT = 472;
  int RLIKE = 473;
  int ROLE = 474;
  int ROLLBACK = 475;
  int ROLLUP = 476;
  int ROUTINE = 477;
  int ROUTINE_CATALOG = 478;
  int ROUTINE_NAME = 479;
  int ROUTINE_SCHEMA = 480;
  int ROW = 481;
  int ROW_COUNT = 482;
  int ROW_NUMBER = 483;
  int ROWS = 484;
  int RUNNING = 485;
  int SATURDAY = 486;
  int SAVEPOINT = 487;
  int SCALAR = 488;
  int SCALE = 489;
  int SCHEMA = 490;
  int SCHEMA_NAME = 491;
  int SCOPE = 492;
  int SCOPE_CATALOGS = 493;
  int SCOPE_NAME = 494;
  int SCOPE_SCHEMA = 495;
  int SCROLL = 496;
  int SEARCH = 497;
  int SECOND = 498;
  int SECONDS = 499;
  int SECTION = 500;
  int SECURITY = 501;
  int SEEK = 502;
  int SELECT = 503;
  int SELF = 504;
  int SENSITIVE = 505;
  int SEPARATOR = 506;
  int SEQUENCE = 507;
  int SERIALIZABLE = 508;
  int SERVER = 509;
  int SERVER_NAME = 510;
  int SESSION = 511;
  int SESSION_USER = 512;
  int SET = 513;
  int SETS = 514;
  int SET_MINUS = 515;
  int SHOW = 516;
  int SIMILAR = 517;
  int SIMPLE = 518;
  int SIZE = 519;
  int SKIP_ = 520;
  int SMALLINT = 521;
  int SOME = 522;
  int SOURCE = 523;
  int SPACE = 524;
  int SPECIFIC = 525;
  int SPECIFIC_NAME = 526;
  int SPECIFICTYPE = 527;
  int SQL = 528;
  int SQLEXCEPTION = 529;
  int SQLSTATE = 530;
  int SQLWARNING = 531;
  int SQL_BIGINT = 532;
  int SQL_BINARY = 533;
  int SQL_BIT = 534;
  int SQL_BLOB = 535;
  int SQL_BOOLEAN = 536;
  int SQL_CHAR = 537;
  int SQL_CLOB = 538;
  int SQL_DATE = 539;
  int SQL_DECIMAL = 540;
  int SQL_DOUBLE = 541;
  int SQL_FLOAT = 542;
  int SQL_INTEGER = 543;
  int SQL_INTERVAL_DAY = 544;
  int SQL_INTERVAL_DAY_TO_HOUR = 545;
  int SQL_INTERVAL_DAY_TO_MINUTE = 546;
  int SQL_INTERVAL_DAY_TO_SECOND = 547;
  int SQL_INTERVAL_HOUR = 548;
  int SQL_INTERVAL_HOUR_TO_MINUTE = 549;
  int SQL_INTERVAL_HOUR_TO_SECOND = 550;
  int SQL_INTERVAL_MINUTE = 551;
  int SQL_INTERVAL_MINUTE_TO_SECOND = 552;
  int SQL_INTERVAL_MONTH = 553;
  int SQL_INTERVAL_SECOND = 554;
  int SQL_INTERVAL_YEAR = 555;
  int SQL_INTERVAL_YEAR_TO_MONTH = 556;
  int SQL_LONGVARBINARY = 557;
  int SQL_LONGVARCHAR = 558;
  int SQL_LONGVARNCHAR = 559;
  int SQL_NCHAR = 560;
  int SQL_NCLOB = 561;
  int SQL_NUMERIC = 562;
  int SQL_NVARCHAR = 563;
  int SQL_REAL = 564;
  int SQL_SMALLINT = 565;
  int SQL_TIME = 566;
  int SQL_TIMESTAMP = 567;
  int SQL_TINYINT = 568;
  int SQL_TSI_DAY = 569;
  int SQL_TSI_FRAC_SECOND = 570;
  int SQL_TSI_HOUR = 571;
  int SQL_TSI_MICROSECOND = 572;
  int SQL_TSI_MINUTE = 573;
  int SQL_TSI_MONTH = 574;
  int SQL_TSI_QUARTER = 575;
  int SQL_TSI_SECOND = 576;
  int SQL_TSI_WEEK = 577;
  int SQL_TSI_YEAR = 578;
  int SQL_VARBINARY = 579;
  int SQL_VARCHAR = 580;
  int SQRT = 581;
  int START = 582;
  int STATE = 583;
  int STATEMENT = 584;
  int STATIC = 585;
  int STDDEV_POP = 586;
  int STDDEV_SAMP = 587;
  int STREAM = 588;
  int STRING_AGG = 589;
  int STRUCTURE = 590;
  int STYLE = 591;
  int SUBCLASS_ORIGIN = 592;
  int SUBMULTISET = 593;
  int SUBSET = 594;
  int SUBSTITUTE = 595;
  int SUBSTRING = 596;
  int SUBSTRING_REGEX = 597;
  int SUCCEEDS = 598;
  int SUM = 599;
  int SUNDAY = 600;
  int SYMMETRIC = 601;
  int SYSTEM = 602;
  int SYSTEM_TIME = 603;
  int SYSTEM_USER = 604;
  int TABLE = 605;
  int TABLE_NAME = 606;
  int TABLESAMPLE = 607;
  int TEMPORARY = 608;
  int THEN = 609;
  int THURSDAY = 610;
  int TIES = 611;
  int TIME = 612;
  int TIME_DIFF = 613;
  int TIME_TRUNC = 614;
  int TIMESTAMP = 615;
  int TIMESTAMPADD = 616;
  int TIMESTAMPDIFF = 617;
  int TIMESTAMP_DIFF = 618;
  int TIMESTAMP_TRUNC = 619;
  int TIMEZONE_HOUR = 620;
  int TIMEZONE_MINUTE = 621;
  int TINYINT = 622;
  int TO = 623;
  int TOP_LEVEL_COUNT = 624;
  int TRAILING = 625;
  int TRANSACTION = 626;
  int TRANSACTIONS_ACTIVE = 627;
  int TRANSACTIONS_COMMITTED = 628;
  int TRANSACTIONS_ROLLED_BACK = 629;
  int TRANSFORM = 630;
  int TRANSFORMS = 631;
  int TRANSLATE = 632;
  int TRANSLATE_REGEX = 633;
  int TRANSLATION = 634;
  int TREAT = 635;
  int TRIGGER = 636;
  int TRIGGER_CATALOG = 637;
  int TRIGGER_NAME = 638;
  int TRIGGER_SCHEMA = 639;
  int TRIM = 640;
  int TRIM_ARRAY = 641;
  int TRUE = 642;
  int TRUNCATE = 643;
  int TUESDAY = 644;
  int TUMBLE = 645;
  int TYPE = 646;
  int UESCAPE = 647;
  int UNBOUNDED = 648;
  int UNCOMMITTED = 649;
  int UNCONDITIONAL = 650;
  int UNDER = 651;
  int UNION = 652;
  int UNIQUE = 653;
  int UNKNOWN = 654;
  int UNPIVOT = 655;
  int UNNAMED = 656;
  int UNNEST = 657;
  int UPDATE = 658;
  int UPPER = 659;
  int UPSERT = 660;
  int USAGE = 661;
  int USER = 662;
  int USER_DEFINED_TYPE_CATALOG = 663;
  int USER_DEFINED_TYPE_CODE = 664;
  int USER_DEFINED_TYPE_NAME = 665;
  int USER_DEFINED_TYPE_SCHEMA = 666;
  int USING = 667;
  int UTF8 = 668;
  int UTF16 = 669;
  int UTF32 = 670;
  int VALUE = 671;
  int VALUES = 672;
  int VALUE_OF = 673;
  int VAR_POP = 674;
  int VAR_SAMP = 675;
  int VARBINARY = 676;
  int VARCHAR = 677;
  int VARYING = 678;
  int VERSION = 679;
  int VERSIONING = 680;
  int VIEW = 681;
  int WEDNESDAY = 682;
  int WEEK = 683;
  int WEEKS = 684;
  int WHEN = 685;
  int WHENEVER = 686;
  int WHERE = 687;
  int WIDTH_BUCKET = 688;
  int WINDOW = 689;
  int WITH = 690;
  int WITHIN = 691;
  int WITHOUT = 692;
  int WORK = 693;
  int WRAPPER = 694;
  int WRITE = 695;
  int XML = 696;
  int YEAR = 697;
  int YEARS = 698;
  int ZONE = 699;
  int UNSIGNED_INTEGER_LITERAL = 700;
  int APPROX_NUMERIC_LITERAL = 701;
  int DECIMAL_NUMERIC_LITERAL = 702;
  int EXPONENT = 703;
  int HEXDIGIT = 704;
  int WHITESPACE = 705;
  int BINARY_STRING_LITERAL = 706;
  int QUOTED_STRING = 707;
  int PREFIXED_STRING_LITERAL = 708;
  int UNICODE_STRING_LITERAL = 709;
  int C_STYLE_ESCAPED_STRING_LITERAL = 710;
  int CHARSETNAME = 711;
  int BIG_QUERY_DOUBLE_QUOTED_STRING = 712;
  int BIG_QUERY_QUOTED_STRING = 713;
  int UNICODE_QUOTED_ESCAPE_CHAR = 714;
  int LPAREN = 715;
  int RPAREN = 716;
  int LBRACE_D = 717;
  int LBRACE_T = 718;
  int LBRACE_TS = 719;
  int LBRACE_FN = 720;
  int LBRACE = 721;
  int RBRACE = 722;
  int LBRACKET = 723;
  int RBRACKET = 724;
  int SEMICOLON = 725;
  int DOT = 726;
  int COMMA = 727;
  int EQ = 728;
  int GT = 729;
  int LT = 730;
  int HOOK = 731;
  int COLON = 732;
  int LE = 733;
  int GE = 734;
  int NE = 735;
  int NE2 = 736;
  int PLUS = 737;
  int MINUS = 738;
  int STAR = 739;
  int SLASH = 740;
  int PERCENT_REMAINDER = 741;
  int CONCAT = 742;
  int NAMED_ARGUMENT_ASSIGNMENT = 743;
  int DOUBLE_PERIOD = 744;
  int QUOTE = 745;
  int DOUBLE_QUOTE = 746;
  int VERTICAL_BAR = 747;
  int CARET = 748;
  int DOLLAR = 749;
  int HINT_BEG = 755;
  int COMMENT_END = 756;
  int SINGLE_LINE_COMMENT = 759;
  int FORMAL_COMMENT = 760;
  int MULTI_LINE_COMMENT = 761;
  int BRACKET_QUOTED_IDENTIFIER = 763;
  int QUOTED_IDENTIFIER = 764;
  int BACK_QUOTED_IDENTIFIER = 765;
  int BIG_QUERY_BACK_QUOTED_IDENTIFIER = 766;
  int HYPHENATED_IDENTIFIER = 767;
  int IDENTIFIER = 768;
  int COLLATION_ID = 769;
  int UNICODE_QUOTED_IDENTIFIER = 770;
  int LETTER = 771;
  int DIGIT = 772;
  int BEL = 773;

  int DEFAULT = 0;
  int DQID = 1;
  int BTID = 2;
  int BQID = 3;
  int BQHID = 4;
  int IN_FORMAL_COMMENT = 5;
  int IN_MULTI_LINE_COMMENT = 6;

  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
    "\"ABS\"",
    "\"ABSENT\"",
    "\"ABSOLUTE\"",
    "\"ACTION\"",
    "\"ADA\"",
    "\"ADD\"",
    "\"ADMIN\"",
    "\"AFTER\"",
    "\"ALL\"",
    "\"ALLOCATE\"",
    "\"ALLOW\"",
    "\"ALTER\"",
    "\"ALWAYS\"",
    "\"AND\"",
    "\"ANY\"",
    "\"APPLY\"",
    "\"ARE\"",
    "\"ARRAY\"",
    "\"ARRAY_AGG\"",
    "\"ARRAY_CONCAT_AGG\"",
    "\"ARRAY_MAX_CARDINALITY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ASENSITIVE\"",
    "\"ASSERTION\"",
    "\"ASSIGNMENT\"",
    "\"ASYMMETRIC\"",
    "\"AT\"",
    "\"ATOMIC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"AUTHORIZATION\"",
    "\"AVG\"",
    "\"BEFORE\"",
    "\"BEGIN\"",
    "\"BEGIN_FRAME\"",
    "\"BEGIN_PARTITION\"",
    "\"BERNOULLI\"",
    "\"BETWEEN\"",
    "\"BIGINT\"",
    "\"BINARY\"",
    "\"BIT\"",
    "\"BLOB\"",
    "\"BOOLEAN\"",
    "\"BOTH\"",
    "\"BREADTH\"",
    "\"BY\"",
    "\"C\"",
    "\"CALL\"",
    "\"CALLED\"",
    "\"CARDINALITY\"",
    "\"CASCADE\"",
    "\"CASCADED\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CATALOG\"",
    "\"CATALOG_NAME\"",
    "\"CEIL\"",
    "\"CEILING\"",
    "\"CENTURY\"",
    "\"CHAIN\"",
    "\"CHAR\"",
    "\"CHAR_LENGTH\"",
    "\"CHARACTER\"",
    "\"CHARACTER_LENGTH\"",
    "\"CHARACTER_SET_CATALOG\"",
    "\"CHARACTER_SET_NAME\"",
    "\"CHARACTER_SET_SCHEMA\"",
    "\"CHARACTERISTICS\"",
    "\"CHARACTERS\"",
    "\"CHECK\"",
    "\"CLASSIFIER\"",
    "\"CLASS_ORIGIN\"",
    "\"CLOB\"",
    "\"CLOSE\"",
    "\"COALESCE\"",
    "\"COBOL\"",
    "\"COLLATE\"",
    "\"COLLATION\"",
    "\"COLLATION_CATALOG\"",
    "\"COLLATION_NAME\"",
    "\"COLLATION_SCHEMA\"",
    "\"COLLECT\"",
    "\"COLUMN\"",
    "\"COLUMN_NAME\"",
    "\"COMMAND_FUNCTION\"",
    "\"COMMAND_FUNCTION_CODE\"",
    "\"COMMIT\"",
    "\"COMMITTED\"",
    "\"CONDITION\"",
    "\"CONDITIONAL\"",
    "\"CONDITION_NUMBER\"",
    "\"CONNECT\"",
    "\"CONNECTION\"",
    "\"CONNECTION_NAME\"",
    "\"CONSTRAINT\"",
    "\"CONSTRAINT_CATALOG\"",
    "\"CONSTRAINT_NAME\"",
    "\"CONSTRAINT_SCHEMA\"",
    "\"CONSTRAINTS\"",
    "\"CONSTRUCTOR\"",
    "\"CONTAINS\"",
    "\"CONTINUE\"",
    "\"CONVERT\"",
    "\"CORR\"",
    "\"CORRESPONDING\"",
    "\"COUNT\"",
    "\"COVAR_POP\"",
    "\"COVAR_SAMP\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CUBE\"",
    "\"CUME_DIST\"",
    "\"CURRENT\"",
    "\"CURRENT_CATALOG\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_DEFAULT_TRANSFORM_GROUP\"",
    "\"CURRENT_PATH\"",
    "\"CURRENT_ROLE\"",
    "\"CURRENT_ROW\"",
    "\"CURRENT_SCHEMA\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"CURRENT_TRANSFORM_GROUP_FOR_TYPE\"",
    "\"CURRENT_USER\"",
    "\"CURSOR\"",
    "\"CURSOR_NAME\"",
    "\"CYCLE\"",
    "\"DATA\"",
    "\"DATABASE\"",
    "\"DATE\"",
    "\"DATE_TRUNC\"",
    "\"DATETIME\"",
    "\"DATETIME_INTERVAL_CODE\"",
    "\"DATETIME_INTERVAL_PRECISION\"",
    "\"DAY\"",
    "\"DAYS\"",
    "\"DEALLOCATE\"",
    "\"DEC\"",
    "\"DECADE\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DEFAULTS\"",
    "\"DEFERRABLE\"",
    "\"DEFERRED\"",
    "\"DEFINE\"",
    "\"DEFINED\"",
    "\"DEFINER\"",
    "\"DEGREE\"",
    "\"DELETE\"",
    "\"DENSE_RANK\"",
    "\"DEPTH\"",
    "\"DEREF\"",
    "\"DERIVED\"",
    "\"DESC\"",
    "\"DESCRIBE\"",
    "\"DESCRIPTION\"",
    "\"DESCRIPTOR\"",
    "\"DETERMINISTIC\"",
    "\"DIAGNOSTICS\"",
    "\"DISALLOW\"",
    "\"DISCONNECT\"",
    "\"DISPATCH\"",
    "\"DISTINCT\"",
    "\"DOMAIN\"",
    "\"DOT\"",
    "\"DOUBLE\"",
    "\"DOW\"",
    "\"DOY\"",
    "\"DROP\"",
    "\"DYNAMIC\"",
    "\"DYNAMIC_FUNCTION\"",
    "\"DYNAMIC_FUNCTION_CODE\"",
    "\"EACH\"",
    "\"ELEMENT\"",
    "\"ELSE\"",
    "\"EMPTY\"",
    "\"ENCODING\"",
    "\"END\"",
    "\"END-EXEC\"",
    "\"END_FRAME\"",
    "\"END_PARTITION\"",
    "\"EPOCH\"",
    "\"EQUALS\"",
    "\"ERROR\"",
    "\"ESCAPE\"",
    "\"EVERY\"",
    "\"EXCEPT\"",
    "\"EXCEPTION\"",
    "\"EXCLUDE\"",
    "\"EXCLUDING\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXP\"",
    "\"EXPLAIN\"",
    "\"EXTEND\"",
    "\"EXTERNAL\"",
    "\"EXTRACT\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FILTER\"",
    "\"FINAL\"",
    "\"FIRST\"",
    "\"FIRST_VALUE\"",
    "\"FLOAT\"",
    "\"FLOOR\"",
    "\"FOLLOWING\"",
    "\"FOR\"",
    "\"FORMAT\"",
    "\"FOREIGN\"",
    "\"FORTRAN\"",
    "\"FOUND\"",
    "\"FRAC_SECOND\"",
    "\"FRAME_ROW\"",
    "\"FREE\"",
    "\"FRIDAY\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"FUSION\"",
    "\"G\"",
    "\"GENERAL\"",
    "\"GENERATED\"",
    "\"GEOMETRY\"",
    "\"GET\"",
    "\"GLOBAL\"",
    "\"GO\"",
    "\"GOTO\"",
    "\"GRANT\"",
    "\"GRANTED\"",
    "\"GROUP\"",
    "\"GROUP_CONCAT\"",
    "\"GROUPING\"",
    "\"GROUPS\"",
    "\"HAVING\"",
    "\"HIERARCHY\"",
    "\"HOLD\"",
    "\"HOP\"",
    "\"HOUR\"",
    "\"HOURS\"",
    "\"IDENTITY\"",
    "\"IGNORE\"",
    "\"ILIKE\"",
    "\"IMMEDIATE\"",
    "\"IMMEDIATELY\"",
    "\"IMPLEMENTATION\"",
    "\"IMPORT\"",
    "\"IN\"",
    "\"INCLUDE\"",
    "\"INCLUDING\"",
    "\"INCREMENT\"",
    "\"INDICATOR\"",
    "\"INITIAL\"",
    "\"INITIALLY\"",
    "\"INNER\"",
    "\"INOUT\"",
    "\"INPUT\"",
    "\"INSENSITIVE\"",
    "\"INSERT\"",
    "\"INSTANCE\"",
    "\"INSTANTIABLE\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTERSECTION\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"INVOKER\"",
    "\"IS\"",
    "\"ISODOW\"",
    "\"ISOYEAR\"",
    "\"ISOLATION\"",
    "\"JAVA\"",
    "\"JOIN\"",
    "\"JSON\"",
    "\"JSON_ARRAY\"",
    "\"JSON_ARRAYAGG\"",
    "\"JSON_EXISTS\"",
    "\"JSON_OBJECT\"",
    "\"JSON_OBJECTAGG\"",
    "\"JSON_QUERY\"",
    "\"JSON_VALUE\"",
    "\"K\"",
    "\"KEY\"",
    "\"KEY_MEMBER\"",
    "\"KEY_TYPE\"",
    "\"LABEL\"",
    "\"LAG\"",
    "\"LANGUAGE\"",
    "\"LARGE\"",
    "\"LAST\"",
    "\"LAST_VALUE\"",
    "\"LATERAL\"",
    "\"LEAD\"",
    "\"LEADING\"",
    "\"LEFT\"",
    "\"LENGTH\"",
    "\"LEVEL\"",
    "\"LIBRARY\"",
    "\"LIKE\"",
    "\"LIKE_REGEX\"",
    "\"LIMIT\"",
    "\"LN\"",
    "\"LOCAL\"",
    "\"LOCALTIME\"",
    "\"LOCALTIMESTAMP\"",
    "\"LOCATOR\"",
    "\"LOWER\"",
    "\"M\"",
    "\"MAP\"",
    "\"MATCH\"",
    "\"MATCHED\"",
    "\"MATCHES\"",
    "\"MATCH_NUMBER\"",
    "\"MATCH_RECOGNIZE\"",
    "\"MAX\"",
    "\"MAXVALUE\"",
    "\"MEASURES\"",
    "\"MEMBER\"",
    "\"MERGE\"",
    "\"MESSAGE_LENGTH\"",
    "\"MESSAGE_OCTET_LENGTH\"",
    "\"MESSAGE_TEXT\"",
    "\"METHOD\"",
    "\"MICROSECOND\"",
    "\"MILLISECOND\"",
    "\"MILLENNIUM\"",
    "\"MIN\"",
    "\"MINUTE\"",
    "\"MINUTES\"",
    "\"MINVALUE\"",
    "\"MOD\"",
    "\"MODIFIES\"",
    "\"MODULE\"",
    "\"MONDAY\"",
    "\"MONTH\"",
    "\"MONTHS\"",
    "\"MORE\"",
    "\"MULTISET\"",
    "\"MUMPS\"",
    "\"NAME\"",
    "\"NAMES\"",
    "\"NANOSECOND\"",
    "\"NATIONAL\"",
    "\"NATURAL\"",
    "\"NCHAR\"",
    "\"NCLOB\"",
    "\"NESTING\"",
    "\"NEW\"",
    "\"NEXT\"",
    "\"NO\"",
    "\"NONE\"",
    "\"NORMALIZE\"",
    "\"NORMALIZED\"",
    "\"NOT\"",
    "\"NTH_VALUE\"",
    "\"NTILE\"",
    "\"NULL\"",
    "\"NULLABLE\"",
    "\"NULLIF\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OBJECT\"",
    "\"OCCURRENCES_REGEX\"",
    "\"OCTET_LENGTH\"",
    "\"OCTETS\"",
    "\"OF\"",
    "\"OFFSET\"",
    "\"OLD\"",
    "\"OMIT\"",
    "\"ON\"",
    "\"ONE\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OPTION\"",
    "\"OPTIONS\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORDERING\"",
    "\"ORDINALITY\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"OUTPUT\"",
    "\"OVER\"",
    "\"OVERLAPS\"",
    "\"OVERLAY\"",
    "\"OVERRIDING\"",
    "\"PAD\"",
    "\"PARAMETER\"",
    "\"PARAMETER_MODE\"",
    "\"PARAMETER_NAME\"",
    "\"PARAMETER_ORDINAL_POSITION\"",
    "\"PARAMETER_SPECIFIC_CATALOG\"",
    "\"PARAMETER_SPECIFIC_NAME\"",
    "\"PARAMETER_SPECIFIC_SCHEMA\"",
    "\"PARTIAL\"",
    "\"PARTITION\"",
    "\"PASCAL\"",
    "\"PASSING\"",
    "\"PASSTHROUGH\"",
    "\"PAST\"",
    "\"PATH\"",
    "\"PATTERN\"",
    "\"PER\"",
    "\"PERCENT\"",
    "\"PERCENTILE_CONT\"",
    "\"PERCENTILE_DISC\"",
    "\"PERCENT_RANK\"",
    "\"PERIOD\"",
    "\"PERMUTE\"",
    "\"PIVOT\"",
    "\"PLACING\"",
    "\"PLAN\"",
    "\"PLI\"",
    "\"PORTION\"",
    "\"POSITION\"",
    "\"POSITION_REGEX\"",
    "\"POWER\"",
    "\"PRECEDES\"",
    "\"PRECEDING\"",
    "\"PRECISION\"",
    "\"PREPARE\"",
    "\"PRESERVE\"",
    "\"PREV\"",
    "\"PRIMARY\"",
    "\"PRIOR\"",
    "\"PRIVILEGES\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"QUARTER\"",
    "\"QUARTERS\"",
    "\"RANGE\"",
    "\"RANK\"",
    "\"READ\"",
    "\"READS\"",
    "\"REAL\"",
    "\"RECURSIVE\"",
    "\"REF\"",
    "\"REFERENCES\"",
    "\"REFERENCING\"",
    "\"REGR_AVGX\"",
    "\"REGR_AVGY\"",
    "\"REGR_COUNT\"",
    "\"REGR_INTERCEPT\"",
    "\"REGR_R2\"",
    "\"REGR_SLOPE\"",
    "\"REGR_SXX\"",
    "\"REGR_SXY\"",
    "\"REGR_SYY\"",
    "\"RELATIVE\"",
    "\"RELEASE\"",
    "\"REPEATABLE\"",
    "\"REPLACE\"",
    "\"RESET\"",
    "\"RESPECT\"",
    "\"RESTART\"",
    "\"RESTRICT\"",
    "\"RESULT\"",
    "\"RETURN\"",
    "\"RETURNED_CARDINALITY\"",
    "\"RETURNED_LENGTH\"",
    "\"RETURNED_OCTET_LENGTH\"",
    "\"RETURNED_SQLSTATE\"",
    "\"RETURNING\"",
    "\"RETURNS\"",
    "\"REVOKE\"",
    "\"RIGHT\"",
    "\"RLIKE\"",
    "\"ROLE\"",
    "\"ROLLBACK\"",
    "\"ROLLUP\"",
    "\"ROUTINE\"",
    "\"ROUTINE_CATALOG\"",
    "\"ROUTINE_NAME\"",
    "\"ROUTINE_SCHEMA\"",
    "\"ROW\"",
    "\"ROW_COUNT\"",
    "\"ROW_NUMBER\"",
    "\"ROWS\"",
    "\"RUNNING\"",
    "\"SATURDAY\"",
    "\"SAVEPOINT\"",
    "\"SCALAR\"",
    "\"SCALE\"",
    "\"SCHEMA\"",
    "\"SCHEMA_NAME\"",
    "\"SCOPE\"",
    "\"SCOPE_CATALOGS\"",
    "\"SCOPE_NAME\"",
    "\"SCOPE_SCHEMA\"",
    "\"SCROLL\"",
    "\"SEARCH\"",
    "\"SECOND\"",
    "\"SECONDS\"",
    "\"SECTION\"",
    "\"SECURITY\"",
    "\"SEEK\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SENSITIVE\"",
    "\"SEPARATOR\"",
    "\"SEQUENCE\"",
    "\"SERIALIZABLE\"",
    "\"SERVER\"",
    "\"SERVER_NAME\"",
    "\"SESSION\"",
    "\"SESSION_USER\"",
    "\"SET\"",
    "\"SETS\"",
    "\"MINUS\"",
    "\"SHOW\"",
    "\"SIMILAR\"",
    "\"SIMPLE\"",
    "\"SIZE\"",
    "\"SKIP\"",
    "\"SMALLINT\"",
    "\"SOME\"",
    "\"SOURCE\"",
    "\"SPACE\"",
    "\"SPECIFIC\"",
    "\"SPECIFIC_NAME\"",
    "\"SPECIFICTYPE\"",
    "\"SQL\"",
    "\"SQLEXCEPTION\"",
    "\"SQLSTATE\"",
    "\"SQLWARNING\"",
    "\"SQL_BIGINT\"",
    "\"SQL_BINARY\"",
    "\"SQL_BIT\"",
    "\"SQL_BLOB\"",
    "\"SQL_BOOLEAN\"",
    "\"SQL_CHAR\"",
    "\"SQL_CLOB\"",
    "\"SQL_DATE\"",
    "\"SQL_DECIMAL\"",
    "\"SQL_DOUBLE\"",
    "\"SQL_FLOAT\"",
    "\"SQL_INTEGER\"",
    "\"SQL_INTERVAL_DAY\"",
    "\"SQL_INTERVAL_DAY_TO_HOUR\"",
    "\"SQL_INTERVAL_DAY_TO_MINUTE\"",
    "\"SQL_INTERVAL_DAY_TO_SECOND\"",
    "\"SQL_INTERVAL_HOUR\"",
    "\"SQL_INTERVAL_HOUR_TO_MINUTE\"",
    "\"SQL_INTERVAL_HOUR_TO_SECOND\"",
    "\"SQL_INTERVAL_MINUTE\"",
    "\"SQL_INTERVAL_MINUTE_TO_SECOND\"",
    "\"SQL_INTERVAL_MONTH\"",
    "\"SQL_INTERVAL_SECOND\"",
    "\"SQL_INTERVAL_YEAR\"",
    "\"SQL_INTERVAL_YEAR_TO_MONTH\"",
    "\"SQL_LONGVARBINARY\"",
    "\"SQL_LONGVARCHAR\"",
    "\"SQL_LONGVARNCHAR\"",
    "\"SQL_NCHAR\"",
    "\"SQL_NCLOB\"",
    "\"SQL_NUMERIC\"",
    "\"SQL_NVARCHAR\"",
    "\"SQL_REAL\"",
    "\"SQL_SMALLINT\"",
    "\"SQL_TIME\"",
    "\"SQL_TIMESTAMP\"",
    "\"SQL_TINYINT\"",
    "\"SQL_TSI_DAY\"",
    "\"SQL_TSI_FRAC_SECOND\"",
    "\"SQL_TSI_HOUR\"",
    "\"SQL_TSI_MICROSECOND\"",
    "\"SQL_TSI_MINUTE\"",
    "\"SQL_TSI_MONTH\"",
    "\"SQL_TSI_QUARTER\"",
    "\"SQL_TSI_SECOND\"",
    "\"SQL_TSI_WEEK\"",
    "\"SQL_TSI_YEAR\"",
    "\"SQL_VARBINARY\"",
    "\"SQL_VARCHAR\"",
    "\"SQRT\"",
    "\"START\"",
    "\"STATE\"",
    "\"STATEMENT\"",
    "\"STATIC\"",
    "\"STDDEV_POP\"",
    "\"STDDEV_SAMP\"",
    "\"STREAM\"",
    "\"STRING_AGG\"",
    "\"STRUCTURE\"",
    "\"STYLE\"",
    "\"SUBCLASS_ORIGIN\"",
    "\"SUBMULTISET\"",
    "\"SUBSET\"",
    "\"SUBSTITUTE\"",
    "\"SUBSTRING\"",
    "\"SUBSTRING_REGEX\"",
    "\"SUCCEEDS\"",
    "\"SUM\"",
    "\"SUNDAY\"",
    "\"SYMMETRIC\"",
    "\"SYSTEM\"",
    "\"SYSTEM_TIME\"",
    "\"SYSTEM_USER\"",
    "\"TABLE\"",
    "\"TABLE_NAME\"",
    "\"TABLESAMPLE\"",
    "\"TEMPORARY\"",
    "\"THEN\"",
    "\"THURSDAY\"",
    "\"TIES\"",
    "\"TIME\"",
    "\"TIME_DIFF\"",
    "\"TIME_TRUNC\"",
    "\"TIMESTAMP\"",
    "\"TIMESTAMPADD\"",
    "\"TIMESTAMPDIFF\"",
    "\"TIMESTAMP_DIFF\"",
    "\"TIMESTAMP_TRUNC\"",
    "\"TIMEZONE_HOUR\"",
    "\"TIMEZONE_MINUTE\"",
    "\"TINYINT\"",
    "\"TO\"",
    "\"TOP_LEVEL_COUNT\"",
    "\"TRAILING\"",
    "\"TRANSACTION\"",
    "\"TRANSACTIONS_ACTIVE\"",
    "\"TRANSACTIONS_COMMITTED\"",
    "\"TRANSACTIONS_ROLLED_BACK\"",
    "\"TRANSFORM\"",
    "\"TRANSFORMS\"",
    "\"TRANSLATE\"",
    "\"TRANSLATE_REGEX\"",
    "\"TRANSLATION\"",
    "\"TREAT\"",
    "\"TRIGGER\"",
    "\"TRIGGER_CATALOG\"",
    "\"TRIGGER_NAME\"",
    "\"TRIGGER_SCHEMA\"",
    "\"TRIM\"",
    "\"TRIM_ARRAY\"",
    "\"TRUE\"",
    "\"TRUNCATE\"",
    "\"TUESDAY\"",
    "\"TUMBLE\"",
    "\"TYPE\"",
    "\"UESCAPE\"",
    "\"UNBOUNDED\"",
    "\"UNCOMMITTED\"",
    "\"UNCONDITIONAL\"",
    "\"UNDER\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNKNOWN\"",
    "\"UNPIVOT\"",
    "\"UNNAMED\"",
    "\"UNNEST\"",
    "\"UPDATE\"",
    "\"UPPER\"",
    "\"UPSERT\"",
    "\"USAGE\"",
    "\"USER\"",
    "\"USER_DEFINED_TYPE_CATALOG\"",
    "\"USER_DEFINED_TYPE_CODE\"",
    "\"USER_DEFINED_TYPE_NAME\"",
    "\"USER_DEFINED_TYPE_SCHEMA\"",
    "\"USING\"",
    "\"UTF8\"",
    "\"UTF16\"",
    "\"UTF32\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"VALUE_OF\"",
    "\"VAR_POP\"",
    "\"VAR_SAMP\"",
    "\"VARBINARY\"",
    "\"VARCHAR\"",
    "\"VARYING\"",
    "\"VERSION\"",
    "\"VERSIONING\"",
    "\"VIEW\"",
    "\"WEDNESDAY\"",
    "\"WEEK\"",
    "\"WEEKS\"",
    "\"WHEN\"",
    "\"WHENEVER\"",
    "\"WHERE\"",
    "\"WIDTH_BUCKET\"",
    "\"WINDOW\"",
    "\"WITH\"",
    "\"WITHIN\"",
    "\"WITHOUT\"",
    "\"WORK\"",
    "\"WRAPPER\"",
    "\"WRITE\"",
    "\"XML\"",
    "\"YEAR\"",
    "\"YEARS\"",
    "\"ZONE\"",
    "<UNSIGNED_INTEGER_LITERAL>",
    "<APPROX_NUMERIC_LITERAL>",
    "<DECIMAL_NUMERIC_LITERAL>",
    "<EXPONENT>",
    "<HEXDIGIT>",
    "<WHITESPACE>",
    "<BINARY_STRING_LITERAL>",
    "<QUOTED_STRING>",
    "<PREFIXED_STRING_LITERAL>",
    "<UNICODE_STRING_LITERAL>",
    "<C_STYLE_ESCAPED_STRING_LITERAL>",
    "<CHARSETNAME>",
    "<BIG_QUERY_DOUBLE_QUOTED_STRING>",
    "<BIG_QUERY_QUOTED_STRING>",
    "<UNICODE_QUOTED_ESCAPE_CHAR>",
    "\"(\"",
    "\")\"",
    "<LBRACE_D>",
    "<LBRACE_T>",
    "<LBRACE_TS>",
    "<LBRACE_FN>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"||\"",
    "\"=>\"",
    "\"..\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"|\"",
    "\"^\"",
    "\"$\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*+\"",
    "\"*/\"",
    "<token of kind 757>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<token of kind 762>",
    "<BRACKET_QUOTED_IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<BACK_QUOTED_IDENTIFIER>",
    "<BIG_QUERY_BACK_QUOTED_IDENTIFIER>",
    "<HYPHENATED_IDENTIFIER>",
    "<IDENTIFIER>",
    "<COLLATION_ID>",
    "<UNICODE_QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<BEL>",
  };

}
